# Generated by Django 3.2.9 on 2023-03-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabrepositorymodel',
            old_name='repository_model',
            new_name='base_repository_model',
        ),
        migrations.RenameField(
            model_name='gitlabrepositorymodel',
            old_name='repo_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gitlabrepositorymodel',
            name='target_ref',
        ),
        migrations.CreateModel(
            name='GitlabRepositoryRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='Наименование параметров')),
                ('description', models.TextField(max_length=64, null=True, verbose_name='Описание параметров')),
                ('parameters', models.JSONField(verbose_name='JSON с параметрами для создания пайплайна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активны ли параметры')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('repository_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitlabapp.gitlabrepositorymodel', verbose_name='Модель репозитория')),
            ],
            options={
                'verbose_name': 'Gitlab. Запуск',
                'verbose_name_plural': 'Gitlab. Запуск',
                'db_table': 'gitlab_runs',
                'ordering': ['created_at', 'updated_at'],
            },
        ),
    ]
