# Generated by Django 3.2.9 on 2023-03-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0002_auto_20230324_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabrepositoryruns',
            name='ref',
            field=models.TextField(default='master', max_length=64, verbose_name='Ветка для запуска пайплайна'),
        ),
    ]
