# Generated by Django 3.2.9 on 2023-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0004_rename_gitlabrepositoryruns_gitlabrepositoryrunsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabrepositoryrunsmodel',
            name='warning_message',
            field=models.TextField(default='', max_length=255, verbose_name='Сообщение-предупреждение'),
        ),
    ]
