# Generated by Django 3.2.9 on 2023-03-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0005_gitlabrepositoryrunsmodel_warning_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabrepositoryrunsmodel',
            old_name='parameters',
            new_name='variables',
        ),
    ]
