# Generated by Django 3.2.9 on 2023-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0007_auto_20230325_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabrepositorypipelinemodel',
            name='source',
        ),
        migrations.AddField(
            model_name='gitlabrepositorypipelinehistorymodel',
            name='source',
            field=models.JSONField(default=dict, verbose_name='Исходный ответ JSON от Gitlab'),
        ),
        migrations.AddField(
            model_name='gitlabrepositorypipelinehistorymodel',
            name='status',
            field=models.TextField(default=None, verbose_name='Статус пайплайна'),
            preserve_default=False,
        ),
    ]
