# Generated by Django 3.2.9 on 2023-03-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0009_auto_20230325_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabrepositoryrunsmodel',
            name='warning_message',
            field=models.TextField(default='', max_length=255, null=True, verbose_name='Сообщение-предупреждение'),
        ),
    ]
