# Generated by Django 3.2.9 on 2023-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapp', '0010_alter_gitlabrepositoryrunsmodel_warning_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabrepositoryrunsmodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=64, null=True, verbose_name='Описание параметров'),
        ),
        migrations.AlterField(
            model_name='gitlabrepositoryrunsmodel',
            name='warning_message',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Сообщение-предупреждение'),
        ),
    ]
