# Generated by Django 3.2.9 on 2023-03-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusermodel',
            name='telegram_user_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Идентификатор пользователя в Telegram'),
        ),
    ]
